### ISSUE TITLE
[Bug] When sees not finished auction using command and number, Bot will crash

### ISSUE THREAD

**Issue by knight-ryu12** [Iyouboushi/mIRC-BattleArena#15]

**Comment by AndrioCelos** [comment]
It looks like the `!auction winners <number>` command is an O(n²) operation. With 10 000 entries, well... 10 000² is a lot.

**Comment by knight-ryu12** [comment]
for represent issue.
!auction info -> !auction winner (current auction number)
bot will  cause crash

2016/09/19 15:17 "Andrio Celos" notifications@github.com:

**Comment by AndrioCelos** [comment]
Specifically, the [`$read`](https://github.com/Iyouboushi/mIRC-BattleArena/blob/master/battlearena/auctionhouse.mrc#L66) function has to:
1. Open the file.
2. Search for the line with the specified number (linear search; O(_n_))
3. Read the line.
4. Close the file.
_each_ time the function is called.
For this sort of application, we can reduce the command's complexity to O(_n_) by using `/fopen` and `$fread` or one of the forms of `$read` that searches for a word, or even further by searching backward (if a recent entry is requested).

**Comment by Iyouboushi** [comment]
Part of the problem, too, is that mIRC can only have so many lines in a text file.  If that threshold is hit then it starts rewriting the lines from the top of the file. Since the Auction House has had so many auctions since it started the file has become a mess. For example, I can't search for the very first auction that ever happened in BA because that line has been overwritten (probably 2 or 3 times by now).

The idea at the time was nice but now I'm wondering if it wouldn't be better to just axe that command all together.
