### ISSUE TITLE
That is not an issue just only an idea

### ISSUE THREAD

**Issue by Serpano** [Iyouboushi/mIRC-BattleArena#22]
hey i have a nice idea for the game can anyone codes a message when a player leveled up ?
at the moment a player must type !level to show the level of him..

it will be better when the bot sends automatically a message... for example

[BattleAreana] Congratutlation Playername is now level 2

for the same when the style is level up the bot sends a message automatically
Do you know what i mean?

**Comment by Pentium320** [comment]
Remind to title your issues/ideas a bit more specifically ;-)

Problem with your idea is, that as the progress is, the faster levels become, and announcing every level for players may become really annoying, on some servers bot can even get kicked for flood, as with dcc chat you can make really fast shopping.

However, this idea could be a bit modified. I can see it with moving such thing to achievements. Let's say, that player gains an achievement for breaking through some level thresholds. For example: 10, 100, 1000, 10000 and 100000. I think, that this could be less "invasive" way to implement it.

**Comment by Serpano** [comment]
okay thanks .. can the master that coding? my idea i has this request from a player on my network..

**Comment by Serpano** [comment]
I mean with styles the bot sends a messages automatically...
so a player asked if exist a method to code this for the level so the player must not type !Level ?

So the bot tells him when he level up for the same by styles ??

You understand?

**Comment by Iyouboushi** [comment]
I think Pentium320 is right... it would cause a ton of flooding spam.  Also style leveling is way different from player leveling as style leveling actually uses xp.

However, there might be a way to do something like this without causing tons of spam.  Maybe I could have the bot set the current level prior to all the stat upgrades then check again after the stat upgrades are done and just display the new level if it's higher.  So instead of seeing "so and so is level 2, 3, 4, 5, 6, 7, 8"  it'd just say "so and so is now level 8" and then tie that to a flag that can be turned on/off on a channel basis.

I'll think about it.

I also like the idea of achievements too.

**Comment by Serpano** [comment]
Iyou when you code this i will thank you for this :) 
Or can you say me what i must modify at the bot to do this ? :)

**Comment by Iyouboushi** [comment]
Added the bot admin command !toggle ShowPlayerLevelUpMsg

When it's on the bot will display the level of someone when they finish buying their stats if their new level is higher than their old level.  It looks like this:

<Iyouboushi> !shop buy str 25
<BattleArena> Iyouboushi's level is now 8157

Note that this is not on by default so bot admins will have to turn it on if they want to see the message.  It probably will be rather spammy at higher levels so that's why it's off by default.

**Comment by Serpano** [comment]
Thank you Iyou Good Job :)

**Comment by AndrioCelos** [comment]
Perhaps it could be appended to the 'You spend red orbs to upgrade your attribute' message.
