### ISSUE TITLE
New Idea request for Weapons

### ISSUE THREAD

**Issue by Serpano** [Iyouboushi/mIRC-BattleArena#24]
Now a Another Question is to show up weapons per categories so the query dont flood..
Example:

[Serpano] !shop list weapons 
[BattleArena] In This Game exists a Lot of Weapons you can buy it with Blackorbs updats with redorbs
[BattleArena] Categories are: Wands, Bow, Guns, Rifles, etc - please type !shop list weapon [category] to show up.

You Understand? 
[Serpano] !shop list weapons Bows:
[BattleArena] New Bow Weapons in Blackorbs: WoodenBow (1), RobinsBow(10), etc

Is this a good idea ?

**Comment by Iyouboushi** [comment]
It's not a bad idea but there are some coding challenges that present itself to make it work right.  If I can figure out how to make it work I'll change it to work like that.

**Comment by Serpano** [comment]
that was nice the bot dont spam.. you see it at the !items command in a previous version this command spams the channel.. you have change it to a better version you can it do so or by same with the !shop list weapon command.. :)

so a player can type !shop list weapons Katanas to show up all katanas in the shop.. and the game should be run faster..
 i think

**Comment by Iyouboushi** [comment]
It's not as easy as the !items because it's possible for bot owners to create custom weapon types and those currently DO show up in the shop as long as the bot owner set it up right. If I change the command to do certain types manually they wouldn't show up in the shop without coding (and I don't want people to have to code).

There's also a problem of some weapon types showing up on multiple lines (Swords and Swords2 for example).  But, again, those don't -have- to be named that as it's possible for bot owners to name it whatever they wanted (they could have named it Swords and MoreSwords or Swords and SwordsTwo, etc).  

All this poses as a serious problem with trying to change the way the shop lists them.

**Comment by Serpano** [comment]
hmm can you code a flag to set this as default for false or dont get this?

**Comment by AndrioCelos** [comment]
Why are there two Swords lists, anyway?

**Comment by Iyouboushi** [comment]
Because in weapons.db the lines were getting too long on some weapons (like swords) so it splits it up into two lines so the bot can actually read it.

**Comment by Iyouboushi** [comment]
Let's leave ISSUES for bugs and actual issues for the bot rather than suggestions.  I've created a Google Document for leaving suggestions and where we can discuss them. 

https://docs.google.com/document/d/1LAvrZH5JMetimigBDAC1ET2MHnuobOhLWTOg0tp-52E/edit
