### ISSUE TITLE
Cell issues - Problem when cell dies the cell_jr's searching for cell.

### ISSUE THREAD

**Issue by Serpano** [Iyouboushi/mIRC-BattleArena#30]
now on my network i modify the boss cell... for example:

MonsterSummon=1
MonsterSummon.Monster=Cell_Jr
MonsterSummon.Chance=30
monstersummon.numberspawn=$rand(1,3)

now here is the problem when cell dies and the cell_jr's are alive and on they own turn...
The bot says: (BattleArena) Error: Cell is not in my Database ...

How can i fix thix ?

**Comment by Iyouboushi** [comment]
I'm not sure what the actual issue is so I'm not sure how to fix it. I just tested with Legion in a normal battle, rather than a portal, and it works.  He summons multiple zombies and then I killed Legion and the zombies continued to fight like normal.

It may be something set wrong in the Jr's files.

**Comment by AndrioCelos** [comment]
Does Cell Jr.'s file refer to Cell at all?

**Comment by Serpano** [comment]
Andrio Celos What did you mean with this ?
Now here is the cell jr file
take a look at this:

[Cell_Jr.zip](https://github.com/Iyouboushi/mIRC-BattleArena/files/716871/Cell_Jr.zip)

**Comment by Tiranadel** [comment]
I'm not seeing anything that would be referencing Cell. Though I would suggest changing the Name= in the Cell Jr file from Name=Cell to Name=Cell Jr to see if that does anything.

**Comment by Serpano** [comment]
i try it...

**Comment by Pentium320** [comment]
I'm only guessing, but this may be related to update, which removes dead monsters from the battle, looks like !cover skill causes troubles there:

```
[04:05:17] <BattleArena> It is Red_Bones's turn [Health Status: Injured Badly] [Status Effects: shocked]
[04:05:24] <BattleArena> Error: Blazebone isn't in my data banks!
```

It's not the first situation, when it happens, though I can't remember where we found same bug.

**Comment by Tiranadel** [comment]
Well, cover only happens if the monster is summoned by the boss/monster. Like whatever Blazebone/Cursed King/Legion/Bob Barbas would summon. Since I see nothing else on the file that references Cell, then that's most likely the thing that's happening.

I'll still suggest that it's a good idea to have Cell Jr's display name as Cell Jr and not Cell to cause any confusion or possible name match issues.
